# Generated by Django 5.2.14 on 2026-05-19 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Klasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchuelerIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schuelerinnen', to='planer.klasse')),
            ],
        ),
        migrations.CreateModel(
            name='Sitzplan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gesamt_glueck', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('solved', 'Gelöst'), ('infeasible', 'Keine Lösung')], default='pending', max_length=20)),
                ('klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sitzplaene', to='planer.klasse')),
            ],
        ),
        migrations.CreateModel(
            name='Tisch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('kapazitaet', models.PositiveIntegerField()),
                ('klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tische', to='planer.klasse')),
            ],
        ),
        migrations.CreateModel(
            name='Zuweisung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schuelerIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planer.schuelerin')),
                ('sitzplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zuweisungen', to='planer.sitzplan')),
                ('tisch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planer.tisch')),
            ],
        ),
        migrations.CreateModel(
            name='TischVorliebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kapazitaet', models.PositiveIntegerField()),
                ('score', models.IntegerField(default=0)),
                ('klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tisch_vorlieben', to='planer.klasse')),
                ('schuelerIn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tisch_vorlieben', to='planer.schuelerin')),
            ],
            options={
                'unique_together': {('schuelerIn', 'kapazitaet')},
            },
        ),
        migrations.CreateModel(
            name='Verboten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verboten', to='planer.klasse')),
                ('schuelerIn_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verboten_als_a', to='planer.schuelerin')),
                ('schuelerIn_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verboten_als_b', to='planer.schuelerin')),
            ],
            options={
                'unique_together': {('schuelerIn_a', 'schuelerIn_b')},
            },
        ),
        migrations.CreateModel(
            name='Vorliebe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=10)),
                ('klasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vorlieben', to='planer.klasse')),
                ('schuelerIn_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vorlieben_als_a', to='planer.schuelerin')),
                ('schuelerIn_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vorlieben_als_b', to='planer.schuelerin')),
            ],
            options={
                'unique_together': {('schuelerIn_a', 'schuelerIn_b')},
            },
        ),
    ]
